-- =============================================================================
-- marts.fct_daily_spend  (TARGET SCHEMA — the normalization goal)
--
-- This is the single unified grain every ad platform gets mapped INTO:
--   one row per  date x channel x campaign x landing_page
-- with metric names normalized (every platform calls these something different).
--
-- We can only finalize the SELECT bodies AFTER the first loads land, because the
-- raw column names differ per source and we agreed to align them against real
-- tables (your answer #1). So this file defines the destination shape + a
-- documented union skeleton. We fill stg_*_spend per platform, then this view
-- just unions them.
-- =============================================================================

create schema if not exists marts;

-- Target columns (the contract the dashboard and agents read against):
--   day            date
--   channel        text   -- 'google' | 'meta' | 'microsoft'
--   campaign_id    text
--   campaign_name  text
--   landing_page_slug text -- parsed from campaign_name, joins ref.map_landing_page_product
--   impressions    bigint
--   clicks         bigint
--   spend          numeric  -- normalized: Google 'cost_micros'/1e6, Meta 'spend', MS 'Spend'
--   conversions    numeric
--   conv_value     numeric  -- platform-reported conversion/revenue value
--   currency       text

-- Once staging views exist, this becomes a simple UNION ALL:
--
-- create or replace view marts.fct_daily_spend as
-- select * from staging.stg_google_spend
-- union all
-- select * from staging.stg_meta_spend
-- union all
-- select * from staging.stg_microsoft_spend;
--
-- And spend-by-product falls out by joining to the mapping table:
--
-- create or replace view marts.fct_daily_spend_by_product as
-- select f.day, m.product_id, m.product_name, f.channel,
--        sum(f.spend) as spend, sum(f.clicks) as clicks,
--        sum(f.conversions) as conversions
-- from marts.fct_daily_spend f
-- left join ref.map_landing_page_product m using (landing_page_slug)
-- group by 1,2,3,4;
