-- =============================================================================
-- marts.fct_product_profit  (TARGET SCHEMA)
--
-- Product-level profit reporting. Combines:
--   + product revenue          (from Shopify orders -> line items)
--   - product COGS             (Shopify variant unit_cost, or ref.product_cost)
--   - allocated ad spend       (marts.fct_daily_spend_by_product)
--   - fees (optional)          (Shopify/processor fees if you want them in)
--
-- Finalized after the Shopify load lands (we map the real line-item column names
-- together). Skeleton below shows the intended join.
-- =============================================================================

create schema if not exists marts;

-- Target columns:
--   period_start   date     -- day or month grain (decide in dashboard step)
--   product_id     text
--   product_name   text
--   units          bigint
--   revenue        numeric
--   cogs           numeric
--   ad_spend       numeric
--   gross_profit   numeric  -- revenue - cogs
--   net_profit     numeric  -- revenue - cogs - ad_spend - fees
--   roas           numeric  -- revenue / nullif(ad_spend,0)

-- Skeleton (column names from Shopify raw to be confirmed after first load):
--
-- create or replace view marts.fct_product_profit as
-- with rev as (
--   select date_trunc('day', li.created_at)::date as day,
--          li.product_id, sum(li.quantity) as units,
--          sum(li.price * li.quantity) as revenue
--   from shopify_raw.orders__line_items li
--   group by 1,2
-- ),
-- cost as (
--   select product_id, unit_cost from shopify_raw.products__variants  -- inventoryItem.unitCost
-- ),
-- spend as (
--   select day, product_id, sum(spend) as ad_spend
--   from marts.fct_daily_spend_by_product group by 1,2
-- )
-- select r.day as period_start, r.product_id, r.units, r.revenue,
--        (r.units * c.unit_cost) as cogs,
--        coalesce(s.ad_spend,0) as ad_spend,
--        r.revenue - (r.units * c.unit_cost) as gross_profit,
--        r.revenue - (r.units * c.unit_cost) - coalesce(s.ad_spend,0) as net_profit,
--        r.revenue / nullif(s.ad_spend,0) as roas
-- from rev r
-- left join cost c using (product_id)
-- left join spend s on s.day = r.day and s.product_id = r.product_id;
